uploads = []
generated = []

[[outputs]]
id = "rr4ymvhTNX5pRxar1VJmA"
uri = "file://COMPARISON.md"
type = "text"
title = "pycleora vs Competitors — Full Feature Comparison"

[[outputs]]
id = "vOlfjIpOjoDgZcXL4fjyw"
uri = "file://cleora-project.tar.gz"
type = "unspecified"
title = "Cleora Project Archive"
