from typing import Any, Iterable, List, Optional, Self, Tuple

import numpy as np
from numpy.typing import NDArray


class SparseMatrix:
    entity_ids: List[str]
    num_entities: int
    num_edges: int
    entity_degrees: NDArray[np.float32]

    def __new__(cls, *args: Any) -> Self: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

    @classmethod
    def from_iterator(
        cls, hyperedges: Iterable[str], columns: str, hyperedge_trim_n: int = 16, num_workers: Optional[int] = None
    ) -> Self: ...

    @classmethod
    def from_files(
        cls, filepaths: list[str], columns: str, hyperedge_trim_n: int = 16, num_workers: Optional[int] = None
    ) -> Self: ...

    def left_markov_propagate(self, x: NDArray[np.float32], num_workers: Optional[int] = None) -> NDArray[np.float32]: ...
    def symmetric_markov_propagate(self, x: NDArray[np.float32], num_workers: Optional[int] = None) -> NDArray[np.float32]: ...
    def get_entity_column_mask(self, column_name: str) -> NDArray[np.bool_]: ...
    def get_entity_index(self, entity_id: str) -> int: ...
    def get_entity_indices(self, entity_ids: List[str]) -> List[int]: ...
    def get_neighbors(self, entity_id: str) -> List[Tuple[str, float]]: ...
    def to_sparse_csr(self, markov_type: Optional[str] = None) -> Tuple[NDArray[np.uint32], NDArray[np.uint32], NDArray[np.float32], int, int]: ...
    def initialize_deterministically(self, feature_dim: int, seed: int = 0) -> NDArray[np.float32]: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
