name: Release

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set the version
        id: version
        run: |
          echo ::set-output name=VERSION::$(($env:GITHUB_REF -split '/')[-1] -replace ' ','')
        env:
          RELEASE_VERSION: $(($env:GITHUB_REF -split '/')[-1] -replace ' ','')

      - name: Check output
        run: |
          echo "test1"
          echo "${env:GITHUB_REF}"
          echo "${env:RELEASE_VERSION}"
          echo $(($env:tag -split '/')[-1] -replace ' ','')
          echo ${{ steps.version.outputs.VERSION }}
          echo "test2"
          echo ${{ steps.version.outputs.VERSION }}
          echo cleora-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked

      - name: Strip binary
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: strip target/release/cleora

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/cleora
          asset_name: cleora-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}
          tag: ${{ github.ref }}